# -*- coding: utf-8 -*-
"""CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNiSFsv0roMvGiqRoz1miv7Kt0n3OdoO
"""

import streamlit as st

st.set_page_config(page_title="Juan Gamero – Interactive CV", layout="centered")

st.title("👨‍💻 Juan Gamero, PhD – Architect who codes - Environmental Designer")
st.markdown("""
I’m an architect and researcher passionate about **automation**, **simulation**, and **sustainability**, with a drive to build **meaningful digital tools for the AEC industry**.
Over the past 7 years, I’ve helped bridge the gap between **design and data-driven insights** — from optimizing passive strategies using **parametric modeling**,
to teaching AI for real estate, to applying **NLP and LLMs** to unstructured AECO documentation.

I thrive in **cross-functional environments** where engineers, architects, and coders collaborate (my four years at DATAI gives evidence of it).
I’ve contributed to research projects that merge **urban data, simulation, and AI**, and I’m eager to develop **custom Revit tools**, **automation workflows**, and **digital twins**
that tackle real-world challenges.

I love turning complex problems into elegant, automated solutions — while actively sharing knowledge, mentoring students and colleagues, and learning from diverse teams.
I’m ready to **collaborate** alongside Reope’s community of coders and AEC visionaries.
""")


# Navigation blobs
option = st.radio("Jump to a section:", ['🎓 Education', '🏢 Work Experience', '📚 Research & Publications', '🧰 Tools & Projects', '💬 Contact'])

if option == '🎓 Education':
    st.subheader("PhD – Environmental & Technological Design in Architecture, University of Navarra")
    st.markdown("2017–2021\n\nFocus: Overheatink risk, passive design, climate strategies, energy simulation")
    st.subheader("Master – Environmental Design and Building Management, University of Navarra")
    st.markdown("2017–2021\n\nFocus: energy in buildings, thermal comfort, water management, life cycle assessment & materials, simulation tools")

elif option == '🏢 Work Experience':
    st.subheader("Institute of Data Science and Artificial Intelligence (DATAI), University of Navarra – Researcher (2021–Present)")

    st.markdown("I currently work as a **researcher** at the [Institute of Data Science and Artificial Intelligence (DATAI)](https://www.unav.edu/web/instituto-de-ciencia-de-los-datos-e-inteligencia-artificial), where I develop data-driven solutions to improve the resilience, performance, and sustainability of the built environment.")

    st.subheader("🌳 AI for Urban Heat & Cooling Resilience")
    st.markdown("Led the *Trees4HeatResilience* project, developing an end-to-end AI pipeline that integrated satellite imagery, image segmentation, and socioeconomic data to assess how urban greenery reduces AC demand.")

    st.subheader("📊 Real Estate Data Science & AI Professor")
    st.markdown("Taught *Data Analysis and Management with Python* in the University of Navarra’s Master in Real Estate (MRE) program (~160 hours).")
    st.markdown("Covered real-world data science workflows: descriptive analytics, visualization tools, and machine learning (supervised + unsupervised) applied to real estate cases.")

    st.subheader("🏡 Building Performance Simulation & Data-Driven Design")
    st.markdown("Delivered insights for residential building design using multi-objective optimization and computational design workflows.")
    st.markdown("Used tools like Grasshopper, Ladybug Tools, Python, Radiance, and EnergyPlus to optimize thermal comfort, cooling loads, and daylight performance.")

    st.subheader("🏢 Digital Twin for Smart Campus")
    st.markdown("Helped create a digital twin of a University of Navarra campus building by integrating sensors, energy simulations, and occupant thermal comfort feedback for accurate energy use predictions.")

    st.subheader("🧠 Applied NLP and LLMs in AEC Industry")
    st.markdown("Supervised PhD research on applying Natural Language Processing (NLP), Large Language Models (LLMs), and triple-based knowledge extraction for automating insights in AECO documents.")

    st.subheader("🥵 Heatwave Vulnerability Diagnostics")
    st.markdown("Investigated design and construction features contributing to indoor overheating during heatwaves. Focused on case studies in Pamplona and Seville to inform heat-resilient retrofits and designs.")



elif option == '📚 Research & Publications':
    st.markdown("### 🧪 Peer-Reviewed Scientific Papers")

    st.markdown("**1.** Gamero-Salinas, J.; López-Fidalgo, J. (2025). *Response Surface Methodology using desirability functions for multiobjective optimization to minimize indoor overheating hours and maximize useful daylight illuminance*. [**Scientific Reports**](https://doi.org/10.1038/s41598-025-96376-x).")

    st.markdown("**2.** Gamero-Salinas, J.; López, M.D.D.; González, M.P.; Arriazu, A.; Monge, A.; Sánchez-Ostiz, A. (2024). *Exploring indoor thermal comfort and its causes and consequences amid heatwaves in a Southern European city – An unsupervised learning approach*. [**Building and Environment**](https://doi.org/10.1016/j.buildenv.2024.111986).")

    st.markdown("**3.** Gamero-Salinas, J.; Kishnani, N.; Sánchez-Ostiz, A.; Monge, A.; Benitez, E. (2022). *Porosity, openness, and exposure: Factors associated with thermal performance in semi-outdoor spaces in tropical Singapore*. [**Energy and Buildings**](https://doi.org/10.1016/j.enbuild.2022.112339).")

    st.markdown("**4.** Gamero-Salinas, J.; Kishnani, N.; Monge, A.; López-Fidalgo, J.; Sánchez-Ostiz, A. (2021). *Evaluation of thermal comfort and building form in tropical semi-outdoor environments*. [**Building and Environment**](https://doi.org/10.1016/j.buildenv.2021.108255).")

    st.markdown("**5.** Gamero-Salinas, J.; Monge, A.; Kishnani, N.; López-Fidalgo, J.; Sánchez-Ostiz, A. (2021). *Passive cooling strategies to lower indoor overheating risk in tropical climates*. [**Energy and Buildings**](https://doi.org/10.1016/j.enbuild.2021.111417).")

    st.markdown("**6.** Gamero-Salinas, J.; Kishnani, N.; Monge, A.; López-Fidalgo, J.; Sánchez-Ostiz, A. (2021). *Building form variables and their influence on semi-outdoor space performance in Singapore*. [**Energy and Buildings**](https://doi.org/10.1016/j.enbuild.2020.110544).")

    st.markdown("**7.** Gamero-Salinas, J.; Monge, A.; Sánchez-Ostiz, A. (2020). *Overheating risk in tropical dwellings during the hottest season*. [**Building and Environment**](https://doi.org/10.1016/j.buildenv.2020.106664).")

    st.markdown("### 📘 Book Chapters")

    st.markdown("**8.** Gamero-Salinas, J. (2023). *Proyecto piloto de recuperación de calor del agua residual para calefacción*. In: **Experiencia: 10 años formando expertos en sostenibilidad**. EUNSA. ISBN 978-84-313-3858-9.")

    st.markdown("**9.** Gamero-Salinas, J.; Monge, A.; Sánchez-Ostiz, A. (2020). *Thermal comfort in a rehabilitated building in Tegucigalpa, Honduras*. In: **REHABEND 2020**. ISBN 978-84-09-17873-5.")

    st.markdown("**10.** Gamero-Salinas, J.; Kishnani, N.; Monge, A.; Gandhi, B.; Bilgi, M.; Sánchez-Ostiz, A. (2020). *Building form and its impact on energy, comfort, and social interaction: A post-occupancy study in Singapore*. In: **PLEA 2020 – Planning Post Carbon Cities**. ISBN 978-84-9749-794-7. [DOI](https://doi.org/10.17979/spudc.9788497497947)")

elif option == '💻 GitHub Projects':
    st.subheader("🌐 GitHub Profile")
    st.markdown("Browse more projects and code at: [github.com/juan-gamero-salinas](https://github.com/juan-gamero-salinas)")

    st.subheader("📦 Climateready Survey – Pamplona")
    st.markdown("Repository: [climateready-survey-pamplona](https://github.com/juan-gamero-salinas/climateready-survey-pamplona)")
    st.markdown("A public dataset and analysis workflow for assessing **heat resilience** and **cooling vulnerability** in Pamplona using survey data and building attributes. Includes data wrangling, exploratory analysis, spatial visualization, and vulnerability scoring.")

    st.subheader("📊 RSM + Desirability Functions for Design Optimization")
    st.markdown("Repository: [rsm-thermal-daylight-optimization](https://github.com/juan-gamero-salinas/rsm-thermal-daylight-optimization)")
    st.markdown("Multi-objective optimization framework using **Response Surface Methodology (RSM)** and **desirability functions** to balance **thermal comfort** and **daylight** in early-stage design. Includes code in R and Python, tied to scientific publication in *Scientific Reports*.")




elif option == '💬 Contact':
    st.markdown("📧 arqgamero@gmail.com")
    st.markdown("[🔗 LinkedIn](https://www.linkedin.com/in/juangamerosalinas/)")